/* Generated By:JavaCC: Do not edit this line. DockerParserConstants.java */
package se.jocke.nb.docker.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DockerParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int SEP = 2;
  /** RegularExpression Id. */
  int LN = 3;
  /** RegularExpression Id. */
  int WHITESPACE = 4;
  /** RegularExpression Id. */
  int FROM = 5;
  /** RegularExpression Id. */
  int MAINTAINER = 6;
  /** RegularExpression Id. */
  int RUN = 7;
  /** RegularExpression Id. */
  int CMD = 8;
  /** RegularExpression Id. */
  int EXPOSE = 9;
  /** RegularExpression Id. */
  int ENV = 10;
  /** RegularExpression Id. */
  int ADD = 11;
  /** RegularExpression Id. */
  int COPY = 12;
  /** RegularExpression Id. */
  int ENTRYPOINT = 13;
  /** RegularExpression Id. */
  int VOLUME = 14;
  /** RegularExpression Id. */
  int USER = 15;
  /** RegularExpression Id. */
  int WORKDIR = 16;
  /** RegularExpression Id. */
  int ONBUILD = 17;
  /** RegularExpression Id. */
  int STRING = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\n\"",
    "<WHITESPACE>",
    "\"FROM\"",
    "\"MAINTAINER\"",
    "\"RUN\"",
    "\"CMD\"",
    "\"EXPOSE\"",
    "\"ENV\"",
    "\"ADD\"",
    "\"COPY\"",
    "\"ENTRYPOINT\"",
    "\"VOLUME\"",
    "\"USER\"",
    "\"WORKDIR\"",
    "\"ONBUILD\"",
    "<STRING>",
  };

}
